# Generated by Django 5.1.4 on 2025-05-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_balance_account_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='session',
            field=models.TextField(blank=True, default='2020-2021', max_length=20, null=True),
        ),
    ]
