# Generated by Django 5.1.4 on 2025-05-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_account_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='session',
            field=models.CharField(blank=True, default='2020-2021', max_length=20, null=True),
        ),
    ]
