# Generated by Django 5.1.4 on 2025-05-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg',
            field=models.IntegerField(blank=True, default='0000', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='roll',
            field=models.IntegerField(blank=True, default='0000000', null=True, unique=True),
        ),
    ]
