# Generated by Django 5.1.4 on 2025-05-19 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_account_reg_alter_account_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='reg',
            field=models.IntegerField(blank=True, default='0000', null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='roll',
            field=models.IntegerField(blank=True, default='0000000', null=True),
        ),
    ]
